version: '3.8'

services:
  app:
    build:
      context: app
      dockerfile: Dockerfile
    volumes:
      - ..:/workspace:cached
    command: sleep infinity
    depends_on:
      - voicevox

  voicevox:
    image: voicevox/voicevox_engine:cpu-latest
    restart: unless-stopped
